name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Cloner le dépôt
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Étape 2 : Configurer l'accès SSH
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

    # Étape 3 : Déployer sur le serveur
    - name: Deploy to Server
      run: |
        ssh root@<your-server-ip> 'bash -s' < deploy.sh
